<?php

$this->closure['setStruttura']=function() {

    $a=array(
        "liz_exec"=>array(
            "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
            "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
        ),
        "liz_tipologia"=>array(
            "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
            "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
        ),
        "liz_locazione"=>array(
            "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
            "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
        ),
        "liz_telaio"=>array(
            "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
            "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
        ),
        "liz_descrizione"=>array(
            "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
            "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
        ),
        "liz_compogomme"=>array(
            "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
            "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
        ),
        "liz_tipogomme"=>array(
            "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
            "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
        ),
        "liz_proprietario"=>array(
            "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
            "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
        ),
        "liz_segno"=>array(
            "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
            "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
        ),
        "liz_usura"=>array(
            "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
            "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
        ),
        "liz_full"=>array(
            "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
            "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
        ),
        "liz_busy"=>array(
            "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
            "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
        )
    );

    $this->form->add_fields($a);

    ///////////////////////////////////////////////

    $a=array(
        "liz_exec"=>"none",
        "liz_tipologia"=>"none",
        "liz_locazione"=>"none",
        "liz_telaio"=>"none",
        "liz_descrizione"=>"none",
        "liz_compogomme"=>"none",
        "liz_tipogomme"=>"none",
        "liz_proprietario"=>"none",
        "liz_segno"=>"none",
        "liz_usura"=>"none",
        "liz_full"=>"none",
        "liz_busy"=>"none"
    );

    $this->form->load_tipi($a);

    ///////////////////////////////////////////////

    $a=array(
        "liz_exec"=>"",
        "liz_tipologia"=>"",
        "liz_locazione"=>"",
        "liz_telaio"=>"",
        "liz_descrizione"=>"",
        "liz_compogomme"=>"",
        "liz_tipogomme"=>"",
        "liz_proprietario"=>"",
        "liz_segno"=>"",
        "liz_usura"=>"",
        "liz_full"=>"",
        "liz_busy"=>""
    );

    $this->form->load_expo($a);

    ///////////////////////////////////////////////

    $a=array(
        "liz_exec"=>"liz_exec",
        "liz_tipologia"=>"liz_tipologia",
        "liz_locazione"=>"liz_locazione",
        "liz_telaio"=>"liz_telaio",
        "liz_descrizione"=>"liz_descrizione",
        "liz_compogomme"=>"liz_compogomme",
        "liz_tipogomme"=>"liz_tipogomme",
        "liz_proprietario"=>"liz_proprietario",
        "liz_segno"=>"liz_segno",
        "liz_usura"=>"liz_usura",
        "liz_full"=>"liz_full",
        "liz_busy"=>"liz_busy"
    );

    $this->form->load_conv($a);

    ///////////////////////////////////////////////

    $a=array(
        "liz_exec"=>array(
            "prop"=>array(
                "input"=>"input",
                "tipo"=>"hidden",
                "maxlenght"=>"",
                "options"=>array(),
                "rows"=>"",
                "default"=>"gdm",
                "placeholder"=>"",
                "disabled"=>false
            ),
            "css"=>array()
        ),
        "liz_tipologia"=>array(
            "prop"=>array(
                "input"=>"select",
                "tipo"=>"",
                "maxlenght"=>"",
                "options"=>array(
                    "Pneumatici"=>array("testo"=>"Pneumatici","disabled"=>false),
                    "Generico"=>array("testo"=>"Generico","disabled"=>false),
                    "TUTTO"=>array("testo"=>"Tutto","disabled"=>false)
                ),
                "rows"=>"",
                "default"=>"Pneumatici",
                "placeholder"=>"",
                "disabled"=>false
            ),
            "css"=>array(
                "width"=>"90%;font-size:1.1em;"
            )
        ),
        "liz_locazione"=>array(
            "prop"=>array(
                "input"=>"input",
                "tipo"=>"text",
                "maxlenght"=>"",
                "options"=>array(),
                "rows"=>"",
                "default"=>"",
                "placeholder"=>"",
                "disabled"=>false
            ),
            "css"=>array(
                "width"=>"90%"
            )
        ),
        "liz_telaio"=>array(
            "prop"=>array(
                "input"=>"input",
                "tipo"=>"text",
                "maxlenght"=>"",
                "options"=>array(),
                "rows"=>"",
                "default"=>"",
                "placeholder"=>"",
                "disabled"=>false
            ),
            "css"=>array(
                "width"=>"90%"
            )
        ),
        "liz_descrizione"=>array(
            "prop"=>array(
                "input"=>"input",
                "tipo"=>"text",
                "maxlenght"=>"",
                "options"=>array(),
                "rows"=>"",
                "default"=>"",
                "placeholder"=>"",
                "disabled"=>false
            ),
            "css"=>array(
                "width"=>"90%"
            )
        ),
        "liz_compogomme"=>array(
            "prop"=>array(
                "input"=>"select",
                "tipo"=>"",
                "maxlenght"=>"",
                "options"=>array(
                    "TRENO"=>array("testo"=>"TRENO","disabled"=>false),
                    "KIT"=>array("testo"=>"KIT","disabled"=>false),
                    "TUTTO"=>array("testo"=>"TUTTO","disabled"=>false)
                ),
                "rows"=>"",
                "default"=>"",
                "placeholder"=>"",
                "disabled"=>false
            ),
            "css"=>array(
                "width"=>"90%;font-size:1.1em;"
            )
        ),
        "liz_tipogomme"=>array(
            "prop"=>array(
                "input"=>"select",
                "tipo"=>"",
                "maxlenght"=>"",
                "options"=>array(
                    "ESTIVO"=>array("testo"=>"ESTIVO","disabled"=>false),
                    "INVERNALE"=>array("testo"=>"INVERNALE","disabled"=>false),
                    "4 STAGIONI"=>array("testo"=>"4 STAGIONI","disabled"=>false),
                    "TUTTO"=>array("testo"=>"TUTTO","disabled"=>false)
                ),
                "rows"=>"",
                "default"=>"",
                "placeholder"=>"",
                "disabled"=>false
            ),
            "css"=>array(
                "width"=>"90%;font-size:1.1em;"
            )
        ),
        "liz_proprietario"=>array(
            "prop"=>array(
                "input"=>"select",
                "tipo"=>"",
                "maxlenght"=>"",
                "options"=>array(
                    "Deposito"=>array("testo"=>"Deposito","disabled"=>false),
                    "Vettura"=>array("testo"=>"Vettura","disabled"=>false),
                    "Cliente"=>array("testo"=>"Cliente","disabled"=>false),
                    "Smaltimento"=>array("testo"=>"Smaltimento","disabled"=>false),
                    "TUTTO"=>array("testo"=>"Tutto","disabled"=>false)
                ),
                "rows"=>"",
                "default"=>"",
                "placeholder"=>"",
                "disabled"=>false
            ),
            "css"=>array(
                "width"=>"90%;font-size:1.1em;"
            )
        ),
        "liz_segno"=>array(
            "prop"=>array(
                "input"=>"select",
                "tipo"=>"",
                "maxlenght"=>"",
                "options"=>array(
                    "min"=>array("testo"=>"Min. uguale","disabled"=>false),
                    "max"=>array("testo"=>"Magg. uguale","disabled"=>false)
                ),
                "rows"=>"",
                "default"=>"",
                "placeholder"=>"",
                "disabled"=>false
            ),
            "css"=>array(
                "width"=>"95%"
            )
        ),
        "liz_usura"=>array(
            "prop"=>array(
                "input"=>"input",
                "tipo"=>"text",
                "maxlenght"=>"",
                "options"=>array(),
                "rows"=>"",
                "default"=>"",
                "placeholder"=>"",
                "disabled"=>false
            ),
            "css"=>array(
                "width"=>"95%"
            )
        ),
        "liz_full"=>array(
            "prop"=>array(
                "input"=>"select",
                "tipo"=>"",
                "maxlenght"=>"",
                "options"=>array(
                    "TUTTO"=>array("testo"=>"Tutto","disabled"=>false),
                    "F"=>array("testo"=>"False","disabled"=>false),
                    "T"=>array("testo"=>"True","disabled"=>false)
                ),
                "rows"=>"",
                "default"=>"TUTTO",
                "placeholder"=>"",
                "disabled"=>false
            ),
            "css"=>array(
                "width"=>"90%"
            )
        ),
        "liz_busy"=>array(
            "prop"=>array(
                "input"=>"select",
                "tipo"=>"",
                "maxlenght"=>"",
                "options"=>array(
                    "TUTTO"=>array("testo"=>"Tutto","disabled"=>false),
                    "F"=>array("testo"=>"False","disabled"=>false),
                    "T"=>array("testo"=>"True","disabled"=>false)
                ),
                "rows"=>"",
                "default"=>"TUTTO",
                "placeholder"=>"",
                "disabled"=>false
            ),
            "css"=>array(
                "width"=>"90%"
            )
        )
    );

    $this->form->load_mappa($a);

    ///////////////////////////////////////////////

   
    $a=array(

        "head"=>array(
            "flag"=>false,
            "height"=>"6",
            "css"=>array(
                "text-align"=>"right;",
                "color"=>"black;",
                "padding-right"=>"10px;",
                "font-weight"=>"bold;",
                "font-size"=>"larger;"
            )
        ),

        "body"=>array(
            
            array(
                "class"=>"",
                "css"=>array(
                    "height"=>"160px;"
                ),
                "blocchi"=>array(
                    array(
                        "class"=>"",
                        "css"=>array(
                            "height"=>"0px;"
                        ),
                        "elementi"=>array(
                            array(
                                "extra"=>"",
                                "prefix"=>"",
                                "label"=>"",
                                "sub"=>"",
                                "map"=>"liz_exec",
                                "css"=>array()
                            )
                        )
                    ),
                    array(
                        "class"=>"",
                        "css"=>array(
                            "width"=>"15%;",
                            "display"=>"inline-block;",
                            "vertical-align"=>"top;"
                        ),
                        "elementi"=>array(
                            array(
                                "extra"=>"",
                                "prefix"=>"",
                                "label"=>"Tipologia",
                                "sub"=>"",
                                "map"=>"liz_tipologia",
                                "css"=>array(
                                    "width"=>"100%;"
                                )
                            ),
                            array(
                                "extra"=>"",
                                "prefix"=>"",
                                "label"=>"Locazione",
                                "sub"=>"",
                                "map"=>"liz_locazione",
                                "css"=>array(
                                    "width"=>"100%;"
                                )
                            )
                        )
                    ),
                    array(
                        "class"=>"",
                        "css"=>array(
                            "width"=>"25%;",
                            "display"=>"inline-block;",
                            "vertical-align"=>"top;"
                        ),
                        "elementi"=>array(
                            array(
                                "extra"=>"",
                                "prefix"=>"",
                                "label"=>"Telaio",
                                "sub"=>"",
                                "map"=>"liz_telaio",
                                "css"=>array(
                                    "width"=>"100%;"
                                )
                            ),
                            array(
                                "extra"=>"",
                                "prefix"=>"",
                                "label"=>"Descrizione",
                                "sub"=>"",
                                "map"=>"liz_descrizione",
                                "css"=>array(
                                    "width"=>"100%;"
                                )
                            )
                        )
                    ),
                    array(
                        "class"=>"",
                        "css"=>array(
                            "width"=>"15%;",
                            "display"=>"inline-block;",
                            "vertical-align"=>"top;"
                        ),
                        "elementi"=>array(
                            array(
                                "extra"=>"",
                                "prefix"=>"",
                                "label"=>"Composizione",
                                "sub"=>"",
                                "map"=>"liz_compogomme",
                                "css"=>array(
                                    "width"=>"100%;"
                                )
                            ),
                            array(
                                "extra"=>"",
                                "prefix"=>"",
                                "label"=>"Tipo Pneumatico",
                                "sub"=>"",
                                "map"=>"liz_tipogomme",
                                "css"=>array(
                                    "width"=>"100%;"
                                )
                            )
                        )
                    ),
                    array(
                        "class"=>"",
                        "css"=>array(
                            "width"=>"20%;",
                            "display"=>"inline-block;",
                            "vertical-align"=>"top;"
                        ),
                        "elementi"=>array(
                            array(
                                "extra"=>"",
                                "prefix"=>"",
                                "label"=>"Proprietario",
                                "sub"=>"",
                                "map"=>"liz_proprietario",
                                "css"=>array(
                                    "width"=>"100%;"
                                )
                            ),
                            array(
                                "extra"=>"",
                                "prefix"=>"",
                                "label"=>"Limite",
                                "sub"=>"",
                                "map"=>"liz_segno",
                                "css"=>array(
                                    "width"=>"59%;",
                                    "display"=>"inline-block;",
                                    "vertical-align"=>"top;"
                                )
                            ),
                            array(
                                "extra"=>"",
                                "prefix"=>"",
                                "label"=>"Usura",
                                "sub"=>"",
                                "map"=>"liz_usura",
                                "css"=>array(
                                    "width"=>"39%;",
                                    "display"=>"inline-block;",
                                    "vertical-align"=>"top;"
                                )
                            )
                        )
                    ),
                    array(
                        "class"=>"",
                        "css"=>array(
                            "width"=>"10%;",
                            "display"=>"inline-block;",
                            "vertical-align"=>"top;"
                        ),
                        "elementi"=>array(
                            array(
                                "extra"=>"",
                                "prefix"=>"",
                                "label"=>"Full",
                                "sub"=>"",
                                "map"=>"liz_full",
                                "css"=>array(
                                    "width"=>"100%;"
                                )
                            ),
                            array(
                                "extra"=>"",
                                "prefix"=>"",
                                "label"=>"Busy",
                                "sub"=>"",
                                "map"=>"liz_busy",
                                "css"=>array(
                                    "width"=>"100%;"
                                )
                            )
                        )
                    ),
                    array(
                        "class"=>"",
                        "css"=>array(
                            "width"=>"14%;",
                            "display"=>"inline-block;",
                            "vertical-align"=>"top;"
                        ),
                        "elementi"=>array(
                            array(
                                "ID"=>"liz_scrivi_button",
                                "extra"=>"button",
                                "prefix"=>"",
                                "label"=>"",
                                "testo"=>"query",
                                "disabled"=>false,
                                "sub"=>"",
                                "map"=>"",
                                "css"=>array(
                                    "position"=>"relative;",
                                    "display"=>"inline-block;",
                                    "width"=>"15%;",
                                    "text-align"=>"center;",
                                    "height"=>"53%;"
                                ),
                                "extraCSS"=>array(
                                    "width"=>"120px;",
                                    "position"=>"relative;",
                                    "top"=>"50%;"
                                )
                            )
                        )
                    )
                ) 
            )
        )
    );

    $this->form->load_struttura($a);

}

?>