<?php
//#####//
//<variante>1</variante>

$this->closure['qcInit']=function() {

    $this->add_fields(
        array(
            "IDcontrollo"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "modulo"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc1"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc1n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc1","op"=>"==","val"=>"0")
            ),
            "qc2"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc2n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc2","op"=>"==","val"=>"0")
            ),
            "qc3"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc3n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc3","op"=>"==","val"=>"0")
            ),
            "qc4"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc4n"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc5"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc5n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc5","op"=>"==","val"=>"0")
            )
        )
    );

    $this->load_tipi(
        array(
            "IDcontrollo"=>"none",
            "modulo"=>"none",
            "qc1"=>"none",
            "qc1n"=>"none",
            "qc2"=>"none",
            "qc2n"=>"none",
            "qc3"=>"none",
            "qc3n"=>"none",
            "qc4"=>"none",
            "qc4n"=>"none",
            "qc5"=>"none",
            "qc5n"=>"none"
        )
    );

    $this->load_expo(
        array(
            "IDcontrollo"=>"",
            "modulo"=>"",
            "qc1"=>"",
            "qc1n"=>"",
            "qc2"=>"",
            "qc2n"=>"",
            "qc3"=>"",
            "qc3n"=>"",
            "qc4"=>"",
            "qc4n"=>"",
            "qc5"=>"",
            "qc5n"=>""
        )
    );

    $this->load_conv(
        array(
            "IDcontrollo"=>"IDcontrollo",
            "modulo"=>"modulo",
            "qc1"=>"qc1",
            "qc1n"=>"qc1n",
            "qc2"=>"qc2",
            "qc2n"=>"qc2n",
            "qc3"=>"qc3",
            "qc3n"=>"qc3n",
            "qc4"=>"qc4",
            "qc4n"=>"qc4n",
            "qc5"=>"qc5",
            "qc5n"=>"qc5n"
        )
    );

    $this->load_mappa(
        array(
            "IDcontrollo"=>array(
                "prop"=>array(
                    "input"=>"input",
                    "tipo"=>"info",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"",
                    "default"=>"",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "modulo"=>array(
                "prop"=>array(
                    "input"=>"input",
                    "tipo"=>"info",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"",
                    "default"=>"",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc1"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc1n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc2"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc2n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc3"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc3n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc4"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc4n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc5"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"2",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc5n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            )
        )
    );

    $this->load_struttura(
        array(

            "head"=>array(
                "flag"=>true,
                "height"=>"6",
                "css"=>array(
                    "text-align"=>"right;",
                    "color"=>"black;",
                    "padding-right"=>"10px;",
                    "font-weight"=>"bold;",
                    "font-size"=>"larger;"
                )
            ),

            "body"=>array(
                
                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Check list lavorazione compilata correttamente:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc1n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc1",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Documentazione in ordine:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc2n",
                                    "css"=>array()
                                ),
                                array(
                                "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc2",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Controllo finale e giro di prova documentati:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc3n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc3",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Lavorazioni spuntate correttamente:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc4n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc4",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Da segnalare:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc5n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc5",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(
                        "margin-top"=>"10px;"
                    ),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(
                                "text-align"=>"center;"
                            ),
                            "elementi"=>array(
                                array(
                                    "extra"=>"button",
                                    "ID"=>"qc_form_confirm",
                                    "testo"=>"chiudi",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"",
                                    "disabled"=>false,
                                    "css"=>array(
                                        "margin-top"=>"10px;"
                                    ),
                                    "extraCSS"=>array(
                                        "font-size"=>"1.4em;"
                                    )
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"IDcontrollo",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"modulo",
                                    "css"=>array()
                                )
                            )
                        )
                    )
                )
            )
        )
    );

    $this->load_score(
        array(
            "qc1"=>array(
                "1"=>array("peso"=>20,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>20,"count"=>0)
            ),
            "qc2"=>array(
                "1"=>array("peso"=>20,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>20,"count"=>0)
            ),
            "qc3"=>array(
                "1"=>array("peso"=>20,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>20,"count"=>0)
            ),
            "qc4"=>array(
                "1"=>array("peso"=>20,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>20,"count"=>0)
            ),
            "qc5"=>array(
                "1"=>array("peso"=>20,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>20,"count"=>-1)
            )
        )
    );

};

$this->closure['customDraw']=function() {

    $this->builder->draw();
    //echo json_encode($this->mappa);
};

$this->closure['customJS']=function() {
    echo '';
};

$this->closure['customCss']=function() {
    echo '';
};

?>