<?php
//#####//
//<variante>1</variante>

$this->closure['qcInit']=function() {

    $this->add_fields(
        array(
            "IDcontrollo"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "modulo"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc1"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc1n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc1","op"=>"==","val"=>"0")
            ),
            "qc2"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc2n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc2","op"=>"==","val"=>"0")
            ),
            "qc3"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc3n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc4"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc4n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc4","op"=>"==","val"=>"0")
            ),
            "qc5"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc5n"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc6"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc6n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc6","op"=>"==","val"=>"0")
            ),
            "qc7"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc7n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc7","op"=>"==","val"=>"0")
            ),
            "qc8"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc8n"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc9"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc9n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc9","op"=>"==","val"=>"0")
            ),
            "qc10"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc10n"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc11"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc11n"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc12"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc12n"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc13"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc13n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc13","op"=>"==","val"=>"0")
            )
        )
    );

    $this->load_tipi(
        array(
            "IDcontrollo"=>"none",
            "modulo"=>"none",
            "qc1"=>"none",
            "qc1n"=>"none",
            "qc2"=>"none",
            "qc2n"=>"none",
            "qc3"=>"none",
            "qc3n"=>"none",
            "qc4"=>"none",
            "qc4n"=>"none",
            "qc5"=>"none",
            "qc5n"=>"none",
            "qc6"=>"none",
            "qc6n"=>"none",
            "qc7"=>"none",
            "qc7n"=>"none",
            "qc8"=>"none",
            "qc8n"=>"none",
            "qc9"=>"none",
            "qc9n"=>"none",
            "qc10"=>"none",
            "qc10n"=>"none",
            "qc11"=>"none",
            "qc11n"=>"none",
            "qc12"=>"none",
            "qc12n"=>"none",
            "qc13"=>"none",
            "qc13n"=>"none"
        )
    );

    $this->load_expo(
        array(
            "IDcontrollo"=>"",
            "modulo"=>"",
            "qc1"=>"",
            "qc1n"=>"",
            "qc2"=>"",
            "qc2n"=>"",
            "qc3"=>"",
            "qc3n"=>"",
            "qc4"=>"",
            "qc4n"=>"",
            "qc5"=>"",
            "qc5n"=>"",
            "qc6"=>"",
            "qc6n"=>"",
            "qc7"=>"",
            "qc7n"=>"",
            "qc8"=>"",
            "qc8n"=>"",
            "qc9"=>"",
            "qc9n"=>"",
            "qc10"=>"",
            "qc10n"=>"",
            "qc11"=>"",
            "qc11n"=>"",
            "qc12"=>"",
            "qc12n"=>"",
            "qc13"=>"",
            "qc13n"=>""
        )
    );

    $this->load_conv(
        array(
            "IDcontrollo"=>"IDcontrollo",
            "modulo"=>"modulo",
            "qc1"=>"qc1",
            "qc1n"=>"qc1n",
            "qc2"=>"qc2",
            "qc2n"=>"qc2n",
            "qc3"=>"qc3",
            "qc3n"=>"qc3n",
            "qc4"=>"qc4",
            "qc4n"=>"qc4n",
            "qc5"=>"qc5",
            "qc5n"=>"qc5n",
            "qc6"=>"qc6",
            "qc6n"=>"qc6n",
            "qc7"=>"qc7",
            "qc7n"=>"qc7n",
            "qc8"=>"qc8",
            "qc8n"=>"qc8n",
            "qc9"=>"qc9",
            "qc9n"=>"qc9n",
            "qc10"=>"qc10",
            "qc10n"=>"qc10n",
            "qc11"=>"qc11",
            "qc11n"=>"qc11n",
            "qc12"=>"qc12",
            "qc12n"=>"qc12n",
            "qc13"=>"qc13",
            "qc13n"=>"qc13n"
        )
    );

    $this->load_mappa(
        array(
            "IDcontrollo"=>array(
                "prop"=>array(
                    "input"=>"input",
                    "tipo"=>"info",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"",
                    "default"=>"",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "modulo"=>array(
                "prop"=>array(
                    "input"=>"input",
                    "tipo"=>"info",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"",
                    "default"=>"",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc1"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc1n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc2"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"2",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc2n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc3"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc3n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc4"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc4n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc5"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc5n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc6"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc6n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc7"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc7n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc8"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc8n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc9"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc9n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc10"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc10n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc11"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc11n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc12"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc12n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc13"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"2",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc13n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            )

        )
    );

    $this->load_struttura(
        array(

            "head"=>array(
                "flag"=>true,
                "height"=>"6",
                "css"=>array(
                    "text-align"=>"right;",
                    "color"=>"black;",
                    "padding-right"=>"10px;",
                    "font-weight"=>"bold;",
                    "font-size"=>"larger;"
                )
            ),

            "body"=>array(
                
                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Utilizzo protezioni abitacolo:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc1n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc1",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Utilizzo protezioni vettura (se rilevabile):",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc2n",
                                    "css"=>array()
                                ),
                                array(
                                "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc2",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Lavorazioni spuntate correttamente:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc3n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc3",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Check list Manutenzione compilata correttamente:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc4n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc4",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Service azzerato correttamente:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc5n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc5",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Impianto tergi conforme all'ordine:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc6n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc6",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Vano motore in ordine e pulito:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc7n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc7",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Vano raccogliacqua pulito:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc8n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc8",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Livelli in ordine:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc9n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc9",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Etichetta manutenzione attaccata:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc10n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc10",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Cerniere lubrificate:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc11n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc11",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Test batteria eseguito:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc12n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc12",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Da segnalare:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc13n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc13",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(
                        "margin-top"=>"10px;"
                    ),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(
                                "text-align"=>"center;"
                            ),
                            "elementi"=>array(
                                array(
                                    "extra"=>"button",
                                    "ID"=>"qc_form_confirm",
                                    "testo"=>"chiudi",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"",
                                    "disabled"=>false,
                                    "css"=>array(
                                        "margin-top"=>"10px;"
                                    ),
                                    "extraCSS"=>array(
                                        "font-size"=>"1.4em;"
                                    )
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"IDcontrollo",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"modulo",
                                    "css"=>array()
                                )
                            )
                        )
                    )
                )
            )
        )
    );

    $this->load_score(
        array(
            "qc1"=>array(
                "1"=>array("peso"=>8,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>8,"count"=>0)
            ),
            "qc2"=>array(
                "1"=>array("peso"=>7,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>7,"count"=>-1)
            ),
            "qc3"=>array(
                "1"=>array("peso"=>8,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>8,"count"=>0)
            ),
            "qc4"=>array(
                "1"=>array("peso"=>8,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>8,"count"=>0)
            ),
            "qc5"=>array(
                "1"=>array("peso"=>8,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>8,"count"=>0)
            ),
            "qc6"=>array(
                "1"=>array("peso"=>8,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>8,"count"=>0)
            ),
            "qc7"=>array(
                "1"=>array("peso"=>8,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>8,"count"=>0)
            ),
            "qc8"=>array(
                "1"=>array("peso"=>8,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>8,"count"=>0)
            ),
            "qc9"=>array(
                "1"=>array("peso"=>8,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>8,"count"=>0)
            ),
            "qc10"=>array(
                "1"=>array("peso"=>7,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>7,"count"=>0)
            ),
            "qc11"=>array(
                "1"=>array("peso"=>7,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>7,"count"=>0)
            ),
            "qc12"=>array(
                "1"=>array("peso"=>8,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>8,"count"=>0)
            ),
            "qc13"=>array(
                "1"=>array("peso"=>7,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>7,"count"=>-1)
            )
        )
    );

};

$this->closure['customDraw']=function() {

    $this->builder->draw();
    //echo json_encode($this->mappa);
};

$this->closure['customJS']=function() {
    echo '';
};

$this->closure['customCss']=function() {
    echo '';
};

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//#####//
//<variante>2</variante>

$this->closure['qcInit']=function() {

    $this->add_fields(
        array(
            "IDcontrollo"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "modulo"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc1"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc1n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc1","op"=>"==","val"=>"0")
            ),
            "qc2"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc2n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc2","op"=>"==","val"=>"0")
            ),
            "qc3"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc3n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc4"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc4n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc4","op"=>"==","val"=>"0")
            ),
            "qc6"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc6n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc6","op"=>"==","val"=>"0")
            ),
            "qc7"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc7n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc7","op"=>"==","val"=>"0")
            ),
            "qc8"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc8n"=>array(
                "js_chk_req"=>array("codice"=>0,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc9"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc9n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc9","op"=>"==","val"=>"0")
            ),
            "qc13"=>array(
                "js_chk_req"=>array("codice"=>1,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"","op"=>"","val"=>"")
            ),
            "qc13n"=>array(
                "js_chk_req"=>array("codice"=>3,"anor"=>"","anand"=>"","anxor"=>""),
                "js_chk_ifreq"=>array("campo"=>"qc13","op"=>"==","val"=>"0")
            )
        )
    );

    $this->load_tipi(
        array(
            "IDcontrollo"=>"none",
            "modulo"=>"none",
            "qc1"=>"none",
            "qc1n"=>"none",
            "qc2"=>"none",
            "qc2n"=>"none",
            "qc3"=>"none",
            "qc3n"=>"none",
            "qc4"=>"none",
            "qc4n"=>"none",
            "qc6"=>"none",
            "qc6n"=>"none",
            "qc7"=>"none",
            "qc7n"=>"none",
            "qc8"=>"none",
            "qc8n"=>"none",
            "qc9"=>"none",
            "qc9n"=>"none",
            "qc13"=>"none",
            "qc13n"=>"none"
        )
    );

    $this->load_expo(
        array(
            "IDcontrollo"=>"",
            "modulo"=>"",
            "qc1"=>"",
            "qc1n"=>"",
            "qc2"=>"",
            "qc2n"=>"",
            "qc3"=>"",
            "qc3n"=>"",
            "qc4"=>"",
            "qc4n"=>"",
            "qc6"=>"",
            "qc6n"=>"",
            "qc7"=>"",
            "qc7n"=>"",
            "qc8"=>"",
            "qc8n"=>"",
            "qc9"=>"",
            "qc9n"=>"",
            "qc13"=>"",
            "qc13n"=>""
        )
    );

    $this->load_conv(
        array(
            "IDcontrollo"=>"IDcontrollo",
            "modulo"=>"modulo",
            "qc1"=>"qc1",
            "qc1n"=>"qc1n",
            "qc2"=>"qc2",
            "qc2n"=>"qc2n",
            "qc3"=>"qc3",
            "qc3n"=>"qc3n",
            "qc4"=>"qc4",
            "qc4n"=>"qc4n",
            "qc6"=>"qc6",
            "qc6n"=>"qc6n",
            "qc7"=>"qc7",
            "qc7n"=>"qc7n",
            "qc8"=>"qc8",
            "qc8n"=>"qc8n",
            "qc9"=>"qc9",
            "qc9n"=>"qc9n",
            "qc13"=>"qc13",
            "qc13n"=>"qc13n"
        )
    );

    $this->load_mappa(
        array(
            "IDcontrollo"=>array(
                "prop"=>array(
                    "input"=>"input",
                    "tipo"=>"info",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"",
                    "default"=>"",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "modulo"=>array(
                "prop"=>array(
                    "input"=>"input",
                    "tipo"=>"info",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"",
                    "default"=>"",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc1"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc1n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc2"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"2",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc2n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc3"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc3n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc4"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc4n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc6"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc6n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc7"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc7n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc8"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc8n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc9"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"1",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc9n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            ),

            "qc13"=>array(
                "prop"=>array(
                    "input"=>"radio",
                    "tipo"=>"3bottom",
                    "maxlenght"=>"",
                    "options"=>array(
                        "1"=>"OK",
                        "0"=>"KO",
                        "2"=>"Non Rilevato"
                    ),
                    "rows"=>"",
                    "default"=>"2",
                    "placeholder"=>"",
                    "disabled"=>false
                ),
                "css"=>array(
                    "width"=>"20px;",
                    "height"=>"20px;"
                )
            ),

            "qc13n"=>array(
                "prop"=>array(
                    "input"=>"textarea",
                    "tipo"=>"",
                    "maxlenght"=>"",
                    "options"=>array(),
                    "rows"=>"2",
                    "default"=>"",
                    "placeholder"=>"note",
                    "disabled"=>false
                ),
                "css"=>array()
            )

        )
    );

    $this->load_struttura(
        array(

            "head"=>array(
                "flag"=>true,
                "height"=>"6",
                "css"=>array(
                    "text-align"=>"right;",
                    "color"=>"black;",
                    "padding-right"=>"10px;",
                    "font-weight"=>"bold;",
                    "font-size"=>"larger;"
                )
            ),

            "body"=>array(
                
                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Utilizzo protezioni abitacolo:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc1n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc1",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Utilizzo protezioni vettura (se rilevabile):",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc2n",
                                    "css"=>array()
                                ),
                                array(
                                "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc2",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Lavorazioni spuntate correttamente:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc3n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc3",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Check list Riparazione/Garanzia compilata correttamente:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc4n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc4",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Impianto tergi conforme all'ordine:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc6n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc6",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Vano motore in ordine e pulito:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc7n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc7",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Vano raccogliacqua pulito:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc8n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc8",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Livelli in ordine:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc9n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc9",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(),
                            "elementi"=>array(
                                array(
                                    "extra"=>"label",
                                    "prefix"=>"numero",
                                    "label"=>"Da segnalare:",
                                    "sub"=>"",
                                    "map"=>"",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc13n",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"qc13",
                                    "css"=>array(
                                        "font-size"=>"1.5em;"
                                    )
                                )
                            )
                        )
                    )
                ),

                array(
                    "class"=>"",
                    "css"=>array(
                        "margin-top"=>"10px;"
                    ),
                    "blocchi"=>array(
                        array(
                            "class"=>"",
                            "css"=>array(
                                "text-align"=>"center;"
                            ),
                            "elementi"=>array(
                                array(
                                    "extra"=>"button",
                                    "ID"=>"qc_form_confirm",
                                    "testo"=>"chiudi",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"",
                                    "disabled"=>false,
                                    "css"=>array(
                                        "margin-top"=>"10px;"
                                    ),
                                    "extraCSS"=>array(
                                        "font-size"=>"1.4em;"
                                    )
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"IDcontrollo",
                                    "css"=>array()
                                ),
                                array(
                                    "extra"=>"",
                                    "prefix"=>"",
                                    "label"=>"",
                                    "sub"=>"",
                                    "map"=>"modulo",
                                    "css"=>array()
                                )
                            )
                        )
                    )
                )
            )
        )
    );

    $this->load_score(
        array(
            "qc1"=>array(
                "1"=>array("peso"=>11,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>11,"count"=>0)
            ),
            "qc2"=>array(
                "1"=>array("peso"=>11,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>11,"count"=>-1)
            ),
            "qc3"=>array(
                "1"=>array("peso"=>12,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>12,"count"=>0)
            ),
            "qc4"=>array(
                "1"=>array("peso"=>11,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>11,"count"=>0)
            ),
            "qc6"=>array(
                "1"=>array("peso"=>11,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>11,"count"=>0)
            ),
            "qc7"=>array(
                "1"=>array("peso"=>11,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>11,"count"=>0)
            ),
            "qc8"=>array(
                "1"=>array("peso"=>11,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>11,"count"=>0)
            ),
            "qc9"=>array(
                "1"=>array("peso"=>11,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>11,"count"=>0)
            ),
            "qc13"=>array(
                "1"=>array("peso"=>11,"count"=>1),
                "0"=>array("peso"=>0,"count"=>1),
                "2"=>array("peso"=>11,"count"=>-1)
            )
        )
    );

};

$this->closure['customDraw']=function() {

    $this->builder->draw();
    //echo json_encode($this->mappa);
};

$this->closure['customJS']=function() {
    echo '';
};

$this->closure['customCss']=function() {
    echo '';
};
?>